name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      TZ: Asia/Tokyo
      RAILS_MASTER_KEY: ${{ secrets.RAILS_TEST_KEY_TEST }}
    services:
      mysql:
        image: mysql:8.4
        volumes:
          - test_mysqlconf.d:/etc/mysql/conf.d
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: work_log_api
          MYSQL_ROOT_HOST: '%'
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby 3.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.x
          bundler-cache: true
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**.yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: rails setup
        run: |
          bundle install
          npm install
          npm install @rollup/rollup-linux-x64-gnu@4.34.8
          mysql -h 127.0.0.1 -P 3306 -u root -pwork_log_api < ./db/setup_for_dev.sql
          bin/rails db:prepare
          bin/rails assets:precompile
      - name: run tests
        run: |
          bundle exec rspec