# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false # [ :email ] と [:email] どちらもOKにする

Style/HashSyntax:
  EnforcedStyle: ruby19 # `:key =>` ではなく `key: value` を許容（既にその方針ならそのままでOK）
