services:
  db:
    image: mysql:9.0.0
    environment:
      MYSQL_ROOT_PASSWORD: work_log_api
      MYSQL_USER: work_log_api_user
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: